title: むつめ祭即売会準備会「コミックさいたま(仮)準備会」
description: >
  むつめ祭即売会「コミックさいたま」のウェブサイト。
baseurl: ""
url: "https://0tu-0w0.github.io/web_comisai/"

author:
  name: コミックさいたま！(仮)準備会
  email: comic.saitdai@gmail.com
  github: comic-saitama-official
  twitter: comisai_offic

plugins:
  - jekyll-paginate
paginate: 5
paginate_path: page:num

sass:
  style: expanded

gems:
  - jekyll-paginate
  - jekyll-feed